# Generated by Django 2.2.6 on 2019-11-16 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=59)),
                ('project_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('projevt_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=15)),
                ('qualification', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('Project', models.ManyToManyField(to='apps.Project')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Department')),
            ],
        ),
    ]
